### ISSUE TITLE
Map should work on IE

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#1]
The map with all the spaces should work on IE Version 11, 11.0.9600.18537. If it's easy, map should also work on v.10 and maybe v.9.

Current Outcome: when opened with IE, the map is blank and all the spaces are listed in text format below the map.

**Comment by namwen** [comment]
The map is supported in Internet Explorer to version 10 as of #5

**Comment by annawb** [comment]
Oh no, @chinmayisk mentioned that she re-adjusted things, and the spaces don't show up anymore! Can you fix this again, please? Can this be ready before Monday?

**Comment by namwen** [comment]
Hmmm, the changes I made are still in the master branch. Are you running it locally or on the heroku instance? It seems that https://ananse-map.herokuapp.com/makermap/index hasn't been updated since these changes were made.

cc: @chinmayisk

**Comment by annawb** [comment]
Ah, that would explain it. Can you please update the heroku instance so I can email the Germans?
