### ISSUE TITLE
Minor Wiki Theme edits

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#100]
On the Wiki page, under the Themes section...

1. Please change Art to "Art and Culture"-- I've fixed the CSV accordingly: http://52.197.65.30:5000/wiki
2. Education appears twice-- please delete the second one:
![image](https://cloud.githubusercontent.com/assets/19519867/23139642/76ce2684-f77b-11e6-880f-d1bec0ea4992.png)

**Comment by albiebrown** [comment]
Did 1 and 2 and also put them in alphabetical order.

**Comment by albiebrown** [comment]
Hey @chinmayisk, I changed Art to "Art and Culture" but that needs to be reflected in the API as well so it finds those spaces. Thanks!

**Comment by albiebrown** [comment]
Some art "Art and Culture" and others are just "Art"...marking this as low priority since it does work

**Comment by annawb** [comment]
I fixed the CSV, so this should all upload as fixed...

**Comment by annawb** [comment]
All fixed
