### ISSUE TITLE
Continued Edit page edits

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#106]
(from my FB chat with csk)

On the edit page:
- "Capabalities" should be spelled "Capabilities"
- Status shows up as blank, even though it should be Active.
- When I click "Cancel" it goes to the page that says "Thank you for your edits" instead of just going directly back to the space page.
- Make Affiliation into Affiliations (plural)
- When spaces already contain a Service, it still shows up as blank in the checkboxes on Edit. Then, if I add a service by checking a box on edit, it deletes the original service.

**Comment by chinmayisk** [comment]
marking as fixed
