### ISSUE TITLE
Wiki page edits

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#107]
(from fb chat with csk)

Wiki edits:
- replace Tags field with Ownership field on Wiki and Edit page
- "Theme" should say "Themes"
- Last Updated and Edit on the left side of the wiki page should be within the other margins.
- the margins in Services and capabilities text overlaps with the text in Tags/Ownership field
- After editing, Tags adds an extra comma to the last item.

Status options on csv:
Active, inactive, planned, unknown

(I deleted "no permanent location" because there were only two-- so these are the only status options now available.)

**Comment by chinmayisk** [comment]
marking as fixed
