### ISSUE TITLE
Make default social media icon NO LINK

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#16]
On the Wiki...

What happens now:
Every one of these social media icons is a link, whether or not there's an actual link to Facebook, Twitter, FabLabs, or whatever:
![image](https://cloud.githubusercontent.com/assets/19519867/22374474/5148b72c-e474-11e6-8572-b9e1a3eb4a0c.png)
Icons that don't link to anything still link to themselves.

What should happen:
Only the icons that actually lead to websites should be links! All the icons without real links should either not have icons (which may be too hard) or should just not be hyperlinks.

**Comment by chinmayisk** [comment]
assigning to self

**Comment by chinmayisk** [comment]
marked as fixed

**Comment by annawb** [comment]
Re-opening, because on IE the cursor still changes to a hand-icon (indicating a link) and links to itself.

**Comment by albiebrown** [comment]
Waiting on @chinmayisk  to get back to me on this

**Comment by albiebrown** [comment]
@chinmayisk I put some Mako logic into the template so if the API returns an empty string for any of the social media links that icon will disappear. This needs to be reflected in the API or however else those link values are getting passed. Thanks!

**Comment by chinmayisk** [comment]
yes @albiebrown your mako logic works now i changed a few things in the backend. Now if there is no link the icon does not show up
