### ISSUE TITLE
Wiki: make website links work

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#17]
On wiki:

What happens now: since I took the "www" or "http://" out of the beginning of the weblinks on the wiki pages, they don't show up as links:
![image](https://cloud.githubusercontent.com/assets/19519867/22375078/a2c025ac-e476-11e6-9915-1212e3ff31e0.png)

What should happen: please make all these website addresses under Contact into hyperlinks!

**Comment by chinmayisk** [comment]
marking as fixed
