### ISSUE TITLE
Wiki top bar misalignment

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#18]
On wiki:

Current issue: Edit, Last Updated, and Mark as Incorrect are all misaligned...
![image](https://cloud.githubusercontent.com/assets/19519867/22375400/ee3f2ae0-e477-11e6-9c88-19cf49e056e1.png)

For future: These should be aligned! Also make Last Updated a few point sizes smaller and put it below... maybe under disclaimer.

**Comment by chinmayisk** [comment]
marking as fixed
