### ISSUE TITLE
Make "Contact Us" button link to an email

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#19]
Currently: "contact us" button on top right of entire website has an empty link

What should happen:
"Contact Us" button should be a hyperlink mailto:anansegroup@gmail.com
![image](https://cloud.githubusercontent.com/assets/19519867/22405237/8bcfa24e-e60d-11e6-9be9-b9571bfeb8cd.png)

**Comment by chinmayisk** [comment]
marking as fixed
