### ISSUE TITLE
Make BMZ logo larger

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#2]
Make the BMZ logo much larger! How would it look if we remove the FAB logo from that corner, and then have a smaller line of mapping partner logos (about 10 logos, including FAB) below the map?

**Comment by annawb** [comment]
I'll make up a mockup of this page.

**Comment by annawb** [comment]
Looks great, thanks! Please update weblink to the English version: https://www.giz.de/en/html/index.html

**Comment by annawb** [comment]
Sorry, I got the link wrong-- please make it link to this site instead: http://www.bmz.de/en/index.html

**Comment by annawb** [comment]
Close this bug as soon as the link works!

**Comment by chinmayisk** [comment]
This is fixed
