### ISSUE TITLE
Retitle Map

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#20]
The current map title is "Innovation Spaces Near And Far"
Please change this to "Crowdsourced Atlas of Community Innovation Spaces"

Also, please add this line in red text right below the map (matching the red color of the (+) button in front of CONTRIBUTE): "We sourced information from different databases and likely have many mistakes – please make corrections! Thanks to our sponsors and (a href="ABOUT PAGE") mapping partners (/a)."

**Comment by chinmayisk** [comment]
assigning to myself

**Comment by chinmayisk** [comment]
marking this as fixed
