### ISSUE TITLE
Map error

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#21]
1.Go to website
2.Click on Map
3.Click on 51(It's present on Pakistan)
4.Click on 4(It's present on Islamabad)
5.Click on 2(It's Present on saidapur)
6.Click on Front locator

Expected Result
The locator should be shown in Austria Map

Actual Result
It is shown in Pakistan map
![image](https://cloud.githubusercontent.com/assets/19519867/22531378/7bb823c4-e8ae-11e6-81a9-a83617e88807.png)

(Unless this is a coordinate error? Please let me know!)

**Comment by annawb** [comment]
Marking as Top-- if this is a coordinate error, it's irrelevant. If it's a coding error, it's a problem!

**Comment by chinmayisk** [comment]
its a co-ordinate error .. so assigning it back to you @annawb  btw flipping co-ordinates it still shows a wrong place can you pls check these co-ordinates ?

**Comment by annawb** [comment]
Strange... ok I'll fix it! Should I send you a csv with the corrected coordinates for the mis-labelled spaces?
