### ISSUE TITLE
Map window not closing

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#22]
Steps to Reproduce
1.Go to Website
2.Click on Map
3.Click on 9 in Iceland
4.Click on Locator(FabLab Vestmannaeyjar)
5.Click on close(dropdown symbol)

Expected Result
The pop up window should be closed

Actual Result
The pop up window doesn't close. It closes when clicked anywhere on map

**Comment by chinmayisk** [comment]
marking as fixed
