### ISSUE TITLE
Map error

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#23]
Steps to Reproduce(UI bug)
1.Go to website
2.Click on Map
3.Click on 9 in Iceland
4.Click on Locator(FabLab Vestmannaeyjar)

Expected Result
The drop down should be same as in UI document

Actual Result
The name of the place over the symbol.

![image](https://cloud.githubusercontent.com/assets/19519867/22531440/c58a0f80-e8ae-11e6-9f45-b638d716fe8b.png)

**Comment by chinmayisk** [comment]
marking it as fixed
