### ISSUE TITLE
Another map window error

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#24]
Steps to Reproduce
1.Go to website
2.Click on Map
3.Click on 9 on Iceland
4.Click on 5
5.Click on 3(Akranes)
6.Click on the locator(Fab Lab Akranes, Innovation Center)
7.Click on Close

Expected Result
It should close the pop up window

Actual Result
It doesn't close the pop up window

**Comment by chinmayisk** [comment]
marking as fixed
