### ISSUE TITLE
Yet another map error

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#25]
Steps to Reproduce
1.Go to website
2.Click on Map
3.Click on 9(Iceland)
4.Click on 5
5.Click on 3(Akranes)
6.Zoom in to Brautir(till the end)

Expected Result
The number should split into locators

Actual Result
The number isn't splitting into locators

RELATED ERROR:
Steps to Reproduce
1.Go to website
2.Click on Map
3.Click on 9(Iceland)
4.Click on 5
5.Click on 3(Akranes)
6.Click on 2(Akranes)
7.Click anywhere on Map

Expected Result
The locators shouldn't merge into number

Actual Result
The locators are merging.

**Comment by namwen** [comment]
This is almost definitely an issue of two spaces sharing the same geo coordinates. The map clustering is actually working fine, it just doesn't show the two spaces until the number cluster is clicked on.

**Comment by annawb** [comment]
Great, it's my problem then!
