### ISSUE TITLE
Map duplicate

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#26]
(Is this a duplicate on the csv? I'll check...)

Steps to Reproduce(two Fab Lab Akranes, Innovation Center Iceland)
1.Go to website
2.Click on Map
3.Click on 9(Iceland)
4.Click on 5
5.Click on 3(Akranes)
6.Click on locator
7.Then Click on 2(Brautir)
8.Click on one of the locator

Expected Result
There shouldn't be two Fab Lab Akranes, Innovation Center Iceland

Actual Result
There are two locators showing Fab Lab Akranes, Innovation Center Iceland

**Comment by chinmayisk** [comment]
yup :)  its the csv problem
