### ISSUE TITLE
Map Popup Issues

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#28]
Steps to Reproduce
1.Go to website
2.Click on Map
3.In world map,click on Iceland
4.Click on Vik
5.Click on close popup

Expected Result
The popup should close.

Actual Result
The popup doesn't close.

**Comment by chinmayisk** [comment]
@namwen is this closed ?

**Comment by chinmayisk** [comment]
This is a major bug

**Comment by chinmayisk** [comment]
This is fixed hence closing the issue
