### ISSUE TITLE
Restructure map filters: Theme | Type | Originator

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#3]
Go to main map on site: http://ananse-map.herokuapp.com 

Current Outcome: At the bottom of the map, the current filter options are Theme, Type, and Originator.

Better Outcome: Replace these with (in order) Types, Themes, and Services. As before, all filters should yield a filtered map of spaces that match that criteria.

Types options: 

- Workshops (Makerspaces, Hackerspaces, Fab Labs, and other spaces focused on tools)
- Hubs (Impact Hubs, Incubators, and other spaces focused on software and/or community events) 
- Events
- Factories
- Shops

Themes options:

●	Biology/Bioengineering
●	Physics
●	Engineering
●	Materials Science
●	Big Data
●	Citizen Science
○	Repair
○	Energy
○	Circular Economy
○	Art and Culture
○	Design
○	Politics
○	Journalism
○	Farming and food
○	Education
○	Local livelihoods
○	Environment
○	Peacekeeping
○	Neighborhood improvements
○	Health
○	Social Justice

Services options:

○	Co-working: temporary office spaces for people working collaboratively or individually from various companies
○	Making: tools for people to make things, either professionally or as hobbyists/tinkerers
○	Hosting events: space for conferences, parties, etc.
○	Selling: a marketplace to sell and/or trade goods
○	Incubating startups: support to get new companies off the ground
○	Educating: formal or informal educational activities
○	Vocational training: education geared toward specific jobs
○	Investing
○	Mentoring: helping people reach their full potential 
○	Donating
○	Transferring technology: introducing new technologies to the community 
○	Co-living: space for people to live together 
○	Repairing
○	Manufacturing: making enough of some product to sell 
○	Prototyping: making the first few versions of some product
○	Researching: academic investigations

**Comment by chinmayisk** [comment]
We can just do two tags i.e types and services since we dont have enough data on all spaces for these three tags

**Comment by namwen** [comment]
Is this the final list of themes?

I pulled all the theme info from the spaces and came up with this list, which doesn't really have any overlap with the above:

> 'Biology', 'Design, Education', 'Art and Culture, Education', 'Appropriate Technology', 'Art and Culture, Design, Politics', 'Education, Art and Culture', 'Politics, ', 'Art and Culture, Design', 'Agriculture', 'Art and Culture, Design, Education', 'Science, Design, Education', 'Media', 'Education', 'Art and Culture, Food, ', 'Art and Culture, ', 'Politics', 'Art and Culture', 'Education, ', 'Science, Art and Culture, Design', 'Design, Science', 'Art', 'Youth', 'Art and Culture, Design, ', 'Science, ', 'Design, Food', 'Design, ', 'Design', 'Appropriate Tech', 'Art and Culture, Politics', 'Appropriate Tech, Art', 'Materials', 'Art and Culture, Science', 'Design, Politics', 'Science', 'Art and Culture, Politics, Education', 'Art and Culture, Food', 'Politics, Art and Culture', 'Science, Design', 'Art and Culture, Design, Food', 'Science, Art and Culture, Politics, Education', 'Appropriate tech', 'Art and Culture, Education, Design', 'Art, Media', 'Education, Design', 'Appropriate Technology, Art', 'Food', 'Design, Art and Culture', 'Science, Art and Culture, Design, Education', 'Art and Culture, Design, Science', 'Design, Art and Culture, Food', 'Art and Culture, Politics, Food, Design', 'Art and Culture, Design, Food, Education', 'Science, Education', 'Design, Politics, Education', 'Science, Art and Culture, ', 'Education, Politics'

**Comment by annawb** [comment]
Sooooo we’re missing a whole bunch of themes, but let’s go with this for now. 

The final list is:
Agriculture
Appropriate Technology (also include ‘appropriate tech’)
Art and Culture (also include ‘art’)
Biology	
Design	
Education
Youth	
Science	
Education
Food	
Materials	
Media	
Politics	

Thanks,
Anna

**Comment by chinmayisk** [comment]
Anna we have to keep uniform naming going forward .. we cant do Art and Culture ( also art) then it will lead to hard coding

**Comment by annawb** [comment]
Somehow, some spaces were listed as “Art and Culture” and some were listed as “Art”. All of these should have been labelled “Art and Culture” instead— this should be corrected on the JSON.
