### ISSUE TITLE
Modify Type filters

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#30]
On the Map, current Type filters are (in order):
_All
Hub
Event
Gallery
Retail
Virtual
Ecovillage
Cluster_ 

Please update so only these options are shown, with the extra text added (in order):
_All
Workshops (Makerspaces, Hackerspaces, Fab Labs, etc.)
Hubs (Tech/Impact Hubs, Incubators, etc)
Events
Ecovillages
Virtual Spaces_

Don't do anything with the spaces themselves-- all the spaces (retail, gallery, cluster, etc) should still show up under "All", but we have so few retail and gallery spaces and most of them are mislabelled anyway... so I don't want to draw anyone's attention to them.

**Comment by chinmayisk** [comment]
@annawb  we are dropping the text in brackets it looks very ugly or we have to make the text size small both of which is not desirable . Hence we will just keep All , Workshops , Hubs , Events , Ecovillages , Virtual Spaces

**Comment by annawb** [comment]
Can you make the font size match the size of the smalltext below the map? I'd like to keep some of the explanations if possible...

**Comment by annawb** [comment]
If it looks bad with a few point sizes smaller, just ignore this and close the bug. I'd just like to have more space for the map itself...

**Comment by chinmayisk** [comment]
I have removed the text in brackets and it looks better now .. making the font smaller does not work
