### ISSUE TITLE
The Goals header doesn't change

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#31]
1. Go to ABOUT page.
2. Click on _Goals_.
Expected result: _Goals_ header is both blue and underlined, and _Team & Partners_ is plaintext.

Current result: _Team & Partners_ is still blue and underlined:
![image](https://cloud.githubusercontent.com/assets/19519867/22570543/c7d7b560-e969-11e6-9a46-d019add2ba53.png)

**Comment by chinmayisk** [comment]
marking as fixed

**Comment by annawb** [comment]
Reopening this issue, because the Goals header still doesn't change on http://52.197.65.30:5000/about/goals

**Comment by annawb** [comment]
Only marking as Top because it looks sloppy...

**Comment by annawb** [comment]
@namwen says: 

"31 is almost definitely fixed. I haven’t been able to reproduce the issue here, both from my local branch and the branch that you pushed to GitHub. If there’s anything wrong on the hosted version, it has to do with a merge issue between your branch and the server."

**Comment by albiebrown** [comment]
I just added a new header snippet for the Goals html, I'm sure Will did it in a cleaner way, but will probably be ok for now...
