### ISSUE TITLE
Thin grey axes on map?

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#32]
On the map, at any zoom level, there are thin grey lines like coordinate axes:
![image](https://cloud.githubusercontent.com/assets/19519867/22593432/65989968-e9ec-11e6-99a2-c028ff47e8de.png)

This shouldn't be present!

**Comment by namwen** [comment]
Woah, strange. I haven't seen this in any browsers. What browser / operating system are you using?

**Comment by annawb** [comment]
Firefox 51.0.1 on a Mac... I'm not sure it always shows up, though. This isn't that important a bug!

**Comment by chinmayisk** [comment]
marking this as minor bug

**Comment by albiebrown** [comment]
Not showing up for me either!
