### ISSUE TITLE
Map: Shrink Type and Theme roll-up bars

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#34]
On map, shrink these Type and Theme roll-up bars and make the text of the labels much smaller-- so you can still navigate the map without feeling claustrophobic.

![image](https://cloud.githubusercontent.com/assets/19519867/22593733/0da8abc4-e9ee-11e6-979b-a49d7f36643d.png)

**Comment by chinmayisk** [comment]
Will, can you take this up ?

**Comment by annawb** [comment]
I include more detail about the same problem on Issue #61

**Comment by annawb** [comment]
Closing to refer to duplicate bug
