### ISSUE TITLE
Landcape mode (UI)

### ISSUE THREAD

**Issue by Ankitaheroorkar** [AnanseGroup/map-of-innovation#43]
In landscape mode in mobile, the map is not much visible.
![screenshot_2017-02-05-22-26-28-02](https://cloud.githubusercontent.com/assets/3414632/22634373/0e8034fa-ec4f-11e6-9e93-7367b4a28b99.png)

**Comment by annawb** [comment]
Let's ask how much they care about the mobile version... or just not mention it...

**Comment by annawb** [comment]
Incidentally fixed!
