### ISSUE TITLE
Type(UI)

### ISSUE THREAD

**Issue by Ankitaheroorkar** [AnanseGroup/map-of-innovation#44]
Pre condition: Tested in internet explorer 11.0.38
In type, all options are not according to UI
![type](https://cloud.githubusercontent.com/assets/3414632/22932250/32758b90-f2ed-11e6-8f90-723e3889b039.png)

**Comment by chinmayisk** [comment]
This is a major bug

**Comment by chinmayisk** [comment]
can some one check this now ?

**Comment by chinmayisk** [comment]
marking this as closed because its fixed from code. Please check on IE and reopen if it is not closed
