### ISSUE TITLE
Theme(UI)

### ISSUE THREAD

**Issue by Ankitaheroorkar** [AnanseGroup/map-of-innovation#45]
Pre condition : Tested in Internet Explorer 11.0.38
In Theme , the list is not displayed according to UI.
![theme](https://cloud.githubusercontent.com/assets/3414632/22932484/18a8edd2-f2ee-11e6-9fcc-dff2bd3e5c91.png)

**Comment by chinmayisk** [comment]
Closing Issue since this seems  appropriate
