### ISSUE TITLE
About page(UI)

### ISSUE THREAD

**Issue by Ankitaheroorkar** [AnanseGroup/map-of-innovation#47]
Pre condition : Tested in Internet Explorer 11.0.38
In about page, the text in blue is not completely visible.
![about](https://cloud.githubusercontent.com/assets/3414632/22933759/93c1122a-f2f2-11e6-8a37-f60571f8a542.png)

**Comment by chinmayisk** [comment]
This is normal in terms of criticality

**Comment by annawb** [comment]
This actually looks really bad-- please fix ASAP. The only text in the blue bar should be the following:

_We’re building a collaborative Atlas of all the community innovation spaces by aggregating existing maps and databases into one giant open-source wiki, and developing an interface to share this data across other websites. Please join us!_

Here is the text for the About section: https://docs.google.com/document/d/1CP6CX2gD366U_dH0hewW6xlvx9Yh0iN9Op6--HgCN88/edit

**Comment by chinmayisk** [comment]
marking as fixed
