### ISSUE TITLE
Link not present

### ISSUE THREAD

**Issue by Ankitaheroorkar** [AnanseGroup/map-of-innovation#48]
Pre condition: tested in Internet Explorer 11.0.38
In Developer Documentation, the link is not present under API.
![doc](https://cloud.githubusercontent.com/assets/3414632/22933916/1300a118-f2f3-11e6-8a64-3056b5f6ff19.png)

**Comment by chinmayisk** [comment]
@annawb what should it link to ?

**Comment by annawb** [comment]
Is there a webpage with the API that you can link to, such as this one for fablabs.io: https://api.fablabs.io/v0/labs.json

Maybe this should link to a specific Github page? I'm not exactly sure what people will be expecting if they want to find our API...

**Comment by annawb** [comment]
Marking as Top because the Germans seem to REALLY care about broken links... if we don't have the API up already, just change the text to "We'll upload our REST API soon, but in the meantime please click here to get involved with Maker.json...."
