### ISSUE TITLE
Wiki Themes and Countries pages

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#51]
Priority: Medium

Go to Wiki --> click on any of the Themes (say, http://52.197.65.30:5000/uifunc/wikilist/theme?name=Art%20and%20Culture ).

Expected result:
There should be a title at the top of the list (use the same formatting as the title "Themes") that says "All spaces with the theme _____"

What happens:
There is a list of spaces without any title reminding you about which Theme you clicked:
![image](https://cloud.githubusercontent.com/assets/19519867/22941337/8e03d122-f2fe-11e6-8956-24aec559259d.png)

There should also be similar titles for the Countries, reminding you which country you're on.

**Comment by chinmayisk** [comment]
marked as fixed
