### ISSUE TITLE
Ananse Group logo link

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#54]
Click on Ananse Group logo on top left.

What should happen: Just get rid of the hyperlink altogether, so it's a static logo. (When we get the domain back from Paul, we'll fix the images on anansegroup.com and then link to that site.)

What currently happens: it links to the About Pylons page.

**Comment by chinmayisk** [comment]
Marking this is as a duplicate to #50 and marking as resolved . Since the original bug is fixed now
