### ISSUE TITLE
User Documentation page formatting

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#55]
On the User Documentation page: http://52.197.65.30:5000/docs 

What should happen:
- The title "Datafields and Definitions" should be in the center.
- Delete this image altogether-- it makes the page too long, so it's not obvious that there's text below.
- Increase the spacing between these two columns of text, because it currently looks bad. If you can't make the columns line up nicely, then scrap the two columns and just have one unified block of text.
- Delete this entire paragraph, since we're not including them on this version:
"Thanks to The Maker Map and Open, we’re including two types of spaces that aren’t actually community-driven, but that are useful for inventing, prototyping, and manufacturing new technologies: Factories and retail Shops. The Factories listed here are all smaller-scale production facilities that want to help you prototype and/or manufacture products, from the state-of-the-art 3D printer farms to the roadside woodworker. These Shops are places to go for your electronics, equipment, and other supplies."

What happens now:
![image](https://cloud.githubusercontent.com/assets/19519867/22942604/96264042-f303-11e6-8df7-ebbba523f966.png)

**Comment by chinmayisk** [comment]
marking as fixed
