### ISSUE TITLE
Margins on Developer Documentation

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#56]
On the Developer Documentation page: http://52.197.65.30:5000/docs/developer

Expected result:
The left and right margins should be exactly the same as the User Documentation page:
![image](https://cloud.githubusercontent.com/assets/19519867/22942859/ac85e526-f304-11e6-9d59-165608d80cb2.png)

Current result:
The text stretches across the entire webpage and looks ugly:
![image](https://cloud.githubusercontent.com/assets/19519867/22942817/7c8bceee-f304-11e6-9b93-59dd7f2e1fdb.png)

**Comment by chinmayisk** [comment]
@namwen consider this as major

**Comment by chinmayisk** [comment]
marking as fixed
