### ISSUE TITLE
Why include empty countries?

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#58]
On the Wiki, the list of Countries contains all the possible countries in the world-- and many of them don't actually have spaces listed. Can you just show the countries that contain spaces, or at least delete the first bunch of countries that don't have anything?

In particular, please delete the following since they're at the top of the list and people are likely to click on them and/or they have weird ?'s:
- ?land
- Andorra
- United Arab Emirates (except I know we should have spaces here....)
- Antigua and Barbuda
- Anguilla
- Saint Barth?lemy
- R?union
- S?o Tom? and Pr?ncipe

**Comment by chinmayisk** [comment]
Have deleted ?land , Andorra , Anguilla. , Saint Barth?lemy and S?o Tom? and Pr?ncipe
Have fixed Reunion 
Have moved UAE to the bottom .. This is another bug can you pls raise a bug for uae and close this ?
