### ISSUE TITLE
Where are UAE spaces?

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#59]
On the United Arab Emirates country page, there are no spaces listed: http://52.197.65.30:5000/uifunc/wikilist/country?name=United%20Arab%20Emirates

But there should be at least 5 spaces there:
![image](https://cloud.githubusercontent.com/assets/19519867/22943816/4b4551a8-f308-11e6-8834-705e2a80c8b9.png)

What's going on? Is this something that's maybe a problem across other countries?

**Comment by chinmayisk** [comment]
will work on this tomorrow apparently the script is not picking up spaces with a space in its name

**Comment by chinmayisk** [comment]
marking as fixed
