### ISSUE TITLE
Firefox issues on Windows (as of Dec 16, 2016)

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#6]
When loading the map on Firefox Version ESR 45.6.0 on Windows (probably Windows 10, but I can check if you can't replicate these issues)...

Problem 1: After loading the map and clicking on a few different spaces, the tag bar comes to the center of the map and the map stops being functional:
![image](https://cloud.githubusercontent.com/assets/19519867/22051041/f73d6146-dd0d-11e6-8620-627ed4573867.png)

Problem 2: After clicking on any of the spaces for more details, the icons (pin2.png) and pictures (space_page.png) sometimes don’t load on the map.

**Comment by chinmayisk** [comment]
reducing the priority of the bug because it has no steps to reproduce. We need to exact information to fix something like this.
