### ISSUE TITLE
Map doesn't cache anymore

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#60]
1. The map used to cache its spaces in Firefox on my Mac, but the platform stopped caching spaces after @namwen fixed some loading issues last month. Now, I have to wait while it reloads every time I click on a different page and then click back to the map. Is there any way to re-instate caching, or whatever was happening earlier? The Germans have specifically complained about this, so I'm calling it a major bug.

2. The map seems to take a while to load, but this isn't urgent-- especially if the caching starts working again!

**Comment by chinmayisk** [comment]
check if it is better for you now ? if not pls define the number of seconds you want it to load in

**Comment by chinmayisk** [comment]
marking it as medium priority bug

**Comment by annawb** [comment]
It still seems kinda slow to load, but maybe it's just the fact that there are so many spaces!

**Comment by annawb** [comment]
(Corrected this bug so it discusses the major issue, which is not caching rather than being slow to load.)

**Comment by annawb** [comment]
Closing, since the problem seems to be mostly fixed.
