### ISSUE TITLE
Map filters too big, poorly formatted

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#61]
Using Firefox on a Mac, click on the map and then expand the Type or Theme filter options.

Expected result:
The filter bar should have much smaller text (probably the same point font as the explanatory text below the map), and the whole bar should overall be smaller so it doesn't ruin the map. The dots should also line up with the text-- to accomplish this, swap the position of "Hubs (Tech/Impact Hubs, Incubators, etc)" with "Events".

Current result: the map filters are too big and the Type filters don't all fit on one line-- making the interface very confusing:
![image](https://cloud.githubusercontent.com/assets/19519867/22944362/dd39f716-f309-11e6-916a-b0f3f67e7ee4.png)

**Comment by chinmayisk** [comment]
Marking it as duplicate to #30
