### ISSUE TITLE
Copy text changes + links

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#62]
Please update all the copy text, by replacing the existing text with any red-highlighted text from this doc: https://docs.google.com/document/d/1CP6CX2gD366U_dH0hewW6xlvx9Yh0iN9Op6--HgCN88/edit

Also, please add all the links! In particular, the User Documentation page is missing all the links marked on this Googledoc: http://52.197.65.30:5000/docs Add underlines to all the hypertext so it's more obviously a link.

Make sure all links are styled in Teal:
- About page
- On bottom of the map
- On User Documentation (ADD LINKS first!)
- On Wiki page (both under Contact Info and new links for Country)

**Comment by chinmayisk** [comment]
marking as fixed

**Comment by annawb** [comment]
Reopening for the following:
1. All links on User Documentation still not working.
2. On Team & Partners, add link to "GIZ, the German Development Agency": https://www.giz.de/en/html/index.html 
3. Contribute text should say: "Do you ever find yourself in some city wondering, where are all the crazy creative people? With your help, we’re building an open-source Atlas of all the community innovation spaces!" (Instead of what it currently says: "Do you ever find yourself in some city wondering, where are all the crazy creative people? We’re building an open-source Atlas of all the community innovation spaces, through partnerships with other databases and random internet people like you.")

**Comment by albiebrown** [comment]
Website currently reflects the state of the google doc and everything is linked and looking good
