### ISSUE TITLE
Label the Status field?

### ISSUE THREAD

**Issue by Ankitaheroorkar** [AnanseGroup/map-of-innovation#63]
Steps to Reproduce
1.Click on Wiki
2.Click on Agriculture
3.Click on Association for Innovation Development of Entrepreneurship in Agriculture 
In that page, "unknown" text is present in center.
![wiki_page](https://cloud.githubusercontent.com/assets/3414632/22989246/2df64ea8-f3db-11e6-9e37-de33b762eb6d.png)

**Comment by chinmayisk** [comment]
The status is written as unknown in the csv hence it shows that @annawb what do you want to show the status as btw this is a database error not coding error. Hence assigning to you

**Comment by annawb** [comment]
Can you label the status for any spaces that currently have a status field? So it says nothing for spaces where the Status is blank, and for anything else it says "Status: unknown" or "Status: active"?

Otherwise, it's not clear what "unknown" or "active" is referring to.

**Comment by chinmayisk** [comment]
assigning to me

**Comment by chinmayisk** [comment]
marking as fixed
