### ISSUE TITLE
Error page in FAROL

### ISSUE THREAD

**Issue by Ankitaheroorkar** [AnanseGroup/map-of-innovation#64]
Steps to Reproduce
1.Click on Wiki
2.Click on Art and Culture
3.Click on FAROL

Expected Result
It should direct to FAROL page

Actual Result
It is showing error page.

http://52.197.65.30:5000/uifunc/wikipage/FAROL20170131154122639117

**Comment by annawb** [comment]
Marking as Top-- this could be a big problem if it happens to multiple spaces!

**Comment by chinmayisk** [comment]
marking as fixed . Should not be an issue for other spaces too
