### ISSUE TITLE
ABOUT page blue box still looks strange

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#66]
What should happen:
The blue box on the ABOUT page http://52.197.65.30:5000/about still doesn't look great. So, please...

1. Shorten the box vertically, so the bottom of the page mostly loads (otherwise it's unclear that there's text below the box)
2. Make the text in the box a few point sizes smaller
3. Edit the text so it just says, "Our collaborative Atlas combines existing databases into one open-source wiki, and shares data across other websites. Please join us!"

What it looks like now:
![image](https://cloud.githubusercontent.com/assets/19519867/23041663/156e6f62-f4af-11e6-8c82-c583993c22be.png)

**Comment by chinmayisk** [comment]
pushing changes marking as fixed.. pls reopen if you dont find changes on checking

**Comment by annawb** [comment]
Looks excellent, thanks!!
