### ISSUE TITLE
Make map bigger

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#67]
Problem: the map doesn't get enough room on the main map page.

Potential solutions:
- DEFINITELY shrink the "Crowdsourced Atlas of Community Innovation Spaces" white bar by as much as possible before it looks too squished. (I know this was the original spec, but I forgot to put in the logo, and at the moment we need more space above and below the text.)
- Shrink the very top margin, above the Ananse Group logo
- Shrink the Contribute bar slightly

Current issue:
![Uploading image.png…]()

**Comment by annawb** [comment]
(Ironically, the map looks much bigger on IE.)

**Comment by chinmayisk** [comment]
marking as fixed
