### ISSUE TITLE
Editing email field shouldn't require exact emails

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#68]
When editing a page such as http://52.197.65.30:5000/editspace?id=BabsonRwandaEntrepreneurshipCenterBREC20170131154122718786 :

What should happen:
I should be able to type in multiple email addresses or phone numbers, in the form "email1@babson.edu, email2@babson.edu"

What currently happens:
The email field requires an actual email address-- which is sensible, except a large number of spaces have multiple emails so this could lead to issues. Ditto with Phone Numbers, as several spaces already have multiple numbers separated by commas.

**Comment by chinmayisk** [comment]
ok i have changed the fields to text
