### ISSUE TITLE
IE: make editing fields larger

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#69]
On IE, when editing a space page:

Expected result:
The Street Address and Description fields should both be large enough to comfortably type/view several sentences-- they should stretch across most of the page, and be 3-4 lines in length (like in Googleforms).

Current result:
![image](https://cloud.githubusercontent.com/assets/19519867/23042634/cac4c700-f4b2-11e6-847e-9f0c1387876a.png)

**Comment by chinmayisk** [comment]
assigning to self

**Comment by chinmayisk** [comment]
closed by mistake

**Comment by chinmayisk** [comment]
marking as fixed
