### ISSUE TITLE
IE: icons within popups on map mis-aligned

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#71]
When loading the map on IE, and clicking on any random space...

Expected result:
Like on my Mac: ![image](https://cloud.githubusercontent.com/assets/19519867/23042919/fa3fc0ec-f4b3-11e6-9daf-4a28a1b6678c.png)

Current result:
![image](https://cloud.githubusercontent.com/assets/19519867/23042889/db56b23a-f4b3-11e6-815c-9e5af8f768d2.png)

Here's what Windows I'm using:
![image](https://cloud.githubusercontent.com/assets/19519867/23042946/195e952a-f4b4-11e6-8cfb-0f1f9f090ec0.png)

**Comment by chinmayisk** [comment]
marking as fixed
