### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Ankitaheroorkar** [AnanseGroup/map-of-innovation#77]
Steps to reproduce
1.Click on wiki
2.Click on Appropriate Technology
3.Click on LAbCeu �guas Lindas de Goi�s

Expected Result
The page should be displayed

Actual Result
It shows server error
"UnicodeDecodeError: 'ascii' codec can't decode byte 0x8d in position 7: ordinal not in range(128)"

**Comment by chinmayisk** [comment]
marking as fixed
