### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Ankitaheroorkar** [AnanseGroup/map-of-innovation#78]
Steps to Reproduce
1.Click on wiki
2.Click on Appropriate Technology
3.Click on Nuvem Esta�ao Rural

Expected Result
It should display the page.

Actual Result
It shows up Server error page.
"UnicodeDecodeError: 'ascii' codec can't decode byte 0x8d in position 10: ordinal not in range(128)"

**Comment by annawb** [comment]
Sounds like a unicode error for all spaces that use the character �...
