### ISSUE TITLE
Website not found

### ISSUE THREAD

**Issue by Ankitaheroorkar** [AnanseGroup/map-of-innovation#80]
Steps to reproduce
1.Click on wiki
2.Click on Appropriate Technology
3.Click on Great Kosa Suaye Technological Centre (workshop of Apostle Safo Kantanka)
4.Click on kantanka.com/technologycentre.html

Expected Result
The website should be displayed

Actual Result
It shows HTTP 404 not found
http://kantanka.com/technologycentre.html

**Comment by annawb** [comment]
Closing because irrelevant to current launch. See #79
