### ISSUE TITLE
Duplicate types on spaces

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#84]
On the Map, many spaces have duplicate types: "Hub, Hub, Workshop" for example:
![screen shot 2017-02-03 at 8 11 29 am](https://cloud.githubusercontent.com/assets/19519867/23128364/ab7bd392-f74c-11e6-9f9e-2eb7e7d1e92d.png)

I think this is because the code currently combines both Primary Type and Types (multiple) datafields. 

I will fix the CSV so you can use ONLY the Types (multiple) datafield, and then you can upload the new CSV and the duplicate types will disappear.

**Comment by annawb** [comment]
Fixed the csv!

**Comment by albiebrown** [comment]
Map.js now dynamically avoids creating duplicates
