### ISSUE TITLE
Font on Wiki pages

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#87]
Make the Wiki titles the same font, color, and size as the Documentation and Licensing page "Helvetica Neus san serif":
![image](https://cloud.githubusercontent.com/assets/19519867/23132328/35bde17c-f75b-11e6-967e-cbe771fc2a88.png)

Current result:
![image](https://cloud.githubusercontent.com/assets/19519867/23132372/61510012-f75b-11e6-9655-a50fc21b2274.png)

**Comment by albiebrown** [comment]
Done
