### ISSUE TITLE
Edit page edits

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#93]
- Services: there's a bug that pre-selects everything: 
![image](https://cloud.githubusercontent.com/assets/19519867/23133338/bd3b960a-f75e-11e6-9a7d-837ce35a3cbe.png)
- Status: include Unknown under drop-down menu:
![image](https://cloud.githubusercontent.com/assets/19519867/23133432/fff76a14-f75e-11e6-8484-9042e006ccad.png)

IF TIME (medium priority):
- Affiliation should be a select-multiple rather than a drop-down menu

**Comment by albiebrown** [comment]
@chinmayisk I ended up cleaning up the template and fixed the checkboxes while I was at it

**Comment by chinmayisk** [comment]
@albiebrown i could not use your changes because it was breaking things.. so i will push the current code after that let try putting this patch again

**Comment by chinmayisk** [comment]
fixed except Affiliations @annawb can you make a seperate bug for that ?
