### ISSUE TITLE
Make formatting template (or something)

### ISSUE THREAD

**Issue by annawb** [AnanseGroup/map-of-innovation#94]
Basically, make everything look better and more uniform!

Chinmayi, please add details to this issue...

**Comment by albiebrown** [comment]
It's looking pretty good now:
![image](https://cloud.githubusercontent.com/assets/6655510/23146648/b02ee44c-f7a6-11e6-99a8-55af7e4b6ff8.png)
![image](https://cloud.githubusercontent.com/assets/6655510/23146655/c067d63e-f7a6-11e6-8b19-90b3674b198c.png)

**Comment by annawb** [comment]
Closing because everything looks great now. Unless there's more to do here?
